---
name: lint

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo -H npm install --global \
              markdownlint-cli
      - name: markdownlint
        run: |
          markdownlint --config .markdownlint.yaml .

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo -H pip install \
              yamllint
      - name: yamllint
        run: |
          yamllint --config-file .yamllint.yaml .
...
